#ifndef SERIALIZER_CONFIG_H
#define SERIALIZER_CONFIG_H

#define ENABLE_QJSON_SERIALIZER         1
#define ENABLE_JSONCPP_SERIALIZER       0
#define ENABLE_RAPIDJSON_SERIALIZER     0
#define ENABLE_RAPIDXML_SERIALIZER      0

#endif
